---
# Source: alluxio/templates/config/alluxio-conf.yaml
#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

# TODO(lu) remove those scripts once worker fuse is enabled in Alluxio kubernetes templates
# These scripts are temporarily put into Overmind because worker fuse is not enabled in the default kubernetes templates
# These scripts are used by mlk8s infestor

apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": before-hook-creation
  name: alluxio-config
  labels:
    name: alluxio-config
    app: alluxio
    chart: alluxio-0.6.5
    release: alluxio
    heritage: Helm
data:
  ALLUXIO_JAVA_OPTS: >- 
    -Dalluxio.master.hostname=alluxio-master-0 
    -Dalluxio.master.journal.type=UFS -Dalluxio.master.journal.folder=/journal -Dalluxio.master.metastore=ROCKS -Dalluxio.master.metastore.inode.cache.max.size=30000000 
    -Dalluxio.security.authorization.permission.enabled=false -Dalluxio.security.authorization.permission.umask=000 -Dalluxio.security.stale.channel.purge.interval=365d 
    -Dalluxio.master.mount.table.root.ufs=s3://S3_IMAGENET_BUCKET/ -Daws.accessKeyId=AWS_ACCESS_KEY -Daws.secretKey=AWS_SECRET_ACCESS_KEY
    -Dalluxio.worker.tieredstore.levels=1 -Dalluxio.worker.tieredstore.level0.dirs.mediumtype=SSD -Dalluxio.worker.tieredstore.level0.alias=SSD -Dalluxio.worker.tieredstore.level0.dirs.path=/alluxio-cache-ssd -Dalluxio.worker.tieredstore.level0.dirs.quota=300GB -Dalluxio.worker.tieredstore.level0.watermark.high.ratio=0.95  -Dalluxio.worker.tieredstore.level0.watermark.low.ratio=0.7 
  ALLUXIO_MASTER_JAVA_OPTS: >-
    -Xms32G -Xmx32G 
    -Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME} 
    -Dalluxio.master.persistence.blacklist=_temporary 
    -Dalluxio.master.rpc.executor.max.pool.size=10240 -Dalluxio.master.rpc.executor.core.pool.size=128 
    -Dalluxio.master.metastore=ROCKS -Dalluxio.master.metastore.inode.cache.max.size=30000000 -Dalluxio.master.journal.log.size.bytes.max=500MB 
  ALLUXIO_JOB_MASTER_JAVA_OPTS: >- 
    -Dalluxio.master.hostname=${ALLUXIO_MASTER_HOSTNAME} 
  ALLUXIO_WORKER_JAVA_OPTS: >-
    -Xmx20G -Xms20G -XX:MaxDirectMemorySize=18g 
    -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME} 
    -Dalluxio.worker.container.hostname=${ALLUXIO_WORKER_CONTAINER_HOSTNAME} 
    -Dalluxio.worker.rpc.port=29999 -Dalluxio.worker.web.port=30000 
    -Dalluxio.worker.data.server.domain.socket.as.uuid=false 
    -Dalluxio.worker.tieredstore.block.locks=100000 
    -Dalluxio.worker.block.master.client.pool.size=1024 
    -Dalluxio.worker.network.reader.buffer.size=32MB 
    -Dalluxio.worker.fuse.enabled=true -Dalluxio.worker.fuse.mount.alluxio.path=/ -Dalluxio.worker.fuse.mount.point=/mnt/alluxio-fuse 
    -Dalluxio.worker.fuse.mount.options=allow_other,kernel_cache,max_read=131072,attr_timeout=7200,entry_timeout=7200 
    -Dalluxio.user.hostname=${ALLUXIO_CLIENT_HOSTNAME} 
    -Dalluxio.user.short.circuit.enabled=true 
    -Dalluxio.user.metadata.cache.enabled=true -Dalluxio.user.metadata.cache.expiration.time=2h -Dalluxio.user.metadata.cache.max.size=10000000 
    -Dalluxio.user.update.file.accesstime.disabled=true 
    -Dalluxio.user.file.passive.cache.enabled=false 
    -Dalluxio.user.logging.threshold=1000ms -Dalluxio.fuse.logging.threshold=1000ms 
    -Dalluxio.user.block.master.client.pool.gc.threshold=1h 
    -Dalluxio.user.block.master.client.pool.size.max=1024 -Dalluxio.user.file.master.client.pool.size.max=1024 -Dalluxio.user.block.worker.client.pool.max=10240 
    -Dalluxio.user.block.read.metrics.enabled=true 
    -Dalluxio.user.file.readtype.default=NO_CACHE 
  ALLUXIO_JOB_WORKER_JAVA_OPTS: >- 
    -Dalluxio.worker.hostname=${ALLUXIO_WORKER_HOSTNAME} -Dalluxio.job.worker.rpc.port=30001 -Dalluxio.job.worker.data.port=30002 -Dalluxio.job.worker.web.port=30003 
  ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH: /alluxio-cache-ssd
